### ISSUE TITLE
Incorrect syntax near the "OFFSET" construct

### ISSUE THREAD

**Issue by KomAuras** [NonFactors/MVC6.Lookup#10]
In code first mode and data in localdb all working correctly.
When I switch to the MSSQL server I get the following errors:
_Incorrect syntax near the "OFFSET" construct. The use of the NEXT parameter in the FETCH instruction is invalid._
![2018-08-14_16-30-29](https://user-images.githubusercontent.com/3600993/44075487-4e4be868-9fe0-11e8-9fbd-c5b879ac6bb8.png)
Tell me please what could be the matter?

**Comment by Muchiachio** [comment]
Did you order lookup data in `GetModels` method?

**Comment by KomAuras** [comment]
```csharp
public override IQueryable<Movie> GetModels()
{
    return Context.Set<Movie>();
}

**Comment by Muchiachio** [comment]
Try ordering it, pagination can't work sometimes without an ordered data.

**Comment by KomAuras** [comment]
Did not help. 
I build test project. If it will not be difficult for you to take a look.
Only need to edit the connection string in ConfigureServices
https://www.clarionlife.net/other/LookupError.zip
Thanks

**Comment by Muchiachio** [comment]
Not sure what is happening, it worked for me, the only thing I did was to downgrade to `2.1.0`, because I don't have `2.1.1` installed. Can you downgrade and check and if it still happens can you try logging the database query, maybe it's malformed by dynamic linq library or entity framework.
![image](https://user-images.githubusercontent.com/6647444/44160567-782bbf80-a0c3-11e8-87ca-1523cc0487bc.png)

**Comment by KomAuras** [comment]
I will watch. I just can not downgrade the version.
By the way, I tried to compile the library with the current version of Core. Still does not work.
Thank you.

**Comment by KomAuras** [comment]
Understood the problem. MSSQL Server 2008 & OFFSET
````csharp
return models.Skip(Filter.Page * Filter.Rows).Take(Filter.Rows);
````

**Comment by Muchiachio** [comment]
And why it doesn't work?

**Comment by KomAuras** [comment]
Need use this UseRowNumberForPaging option in DBContext (for old SLQ servers).
The question can be covered. Many thanks for your support.
