### ISSUE TITLE
How to use lookup with .net core 2.1 Razor page model

### ISSUE THREAD

**Issue by RajeshDhalange** [NonFactors/MVC6.Lookup#11]

**Comment by Muchiachio** [comment]
What doesn't work when used the same way as in asp pages but with `Url.Page` links?

**Comment by RajeshDhalange** [comment]
<div mvc-lookup-for="Id" url="AllPeople" title="People"></div>

when adding this line giving following error

Error	CS0411	The type arguments for method 'IModelExpressionProvider.CreateModelExpression<TModel, TValue>(ViewDataDictionary<TModel>, Expression<Func<TModel, TValue>>)' cannot be inferred from the usage. Try specifying the type

**Comment by RajeshDhalange** [comment]
Can you please provide the example of Razor page with PageMode instead of Controller

**Comment by Muchiachio** [comment]
Not like it's different, asp net documentation doesn't provide a separate example for each of it's tag helpers so I don't see a reason to explicitly show razor pages. With that said I will see if I can repro it.

For now you can use the older `Html.LookupFor` [syntax](http://mvc-datalist.azurewebsites.net/).
Just change `Datalist` to `Lookup` and it should be the same in those examples.

**Comment by Muchiachio** [comment]
I don't get the error, it looks like you have your project miss configured, can you check if normal tag helpers work or throw the same error? If they don't can you please share a repro?

**Comment by RajeshDhalange** [comment]
Thank you for hints for MVVM model URL should be like **url="HomeSearch?handler=AllPeople"** so not method gets called.
But do me a favor give sample code for PeopleLookup class for pre-populated array list from the database instead of Entity framework.

**Comment by Muchiachio** [comment]
I'm not sure what data provider you are using, but you should know how to make a list of data. So I can't give a specific example. But any list of data should work fine, you can even use simple arrays if you want to
```c#
public override IQueryable<Person> GetModels()
{
    return new[] { new Person() }.AsQueryable();
}
```

**Comment by Muchiachio** [comment]
Do you get this request when pressing the browse button? I think you are giving a `0` value for the `Id` and lookup tries to load the data for that id after page loads and doesn't find it, selecting other items should work.

**Comment by RajeshDhalange** [comment]
Problem solve. Thank you for your UI Lookup and Grid control you are the best
