### ISSUE TITLE
do you have decision for write this control by .net core ? 

### ISSUE THREAD

**Issue by sajadghobadi** [NonFactors/MVC6.Lookup#12]
hi. thank you for nice lookup control.
do you have decision for write this control by .net core ? 
now, it depends to .net framework 4.6, so i cant use it because maybe in future  deploy my app in linux server.

**Comment by Muchiachio** [comment]
It target both `net46+` and `netstandard1.6+`. Does it not compile in your core app?

**Comment by sajadghobadi** [comment]
of course it compiled, but i need to run compiled code in linux server(use .net core cross platform capability), so i think if my code compile by .net framework 4.6 dependency it dose not run on linux.

**Comment by Muchiachio** [comment]
Yes, so compile it on net core? :D

**Comment by MerkavaPL** [comment]
Controls work fine on Core. Never used .NET 4.X at all. Run in Asp Core on Linux for the last 12+ months.
