### ISSUE TITLE
ASP.NET Core 3.0 Support

### ISSUE THREAD

**Issue by caleblanchard** [NonFactors/MVC6.Lookup#14]
ASP.NET Core has now been officially released and I have upgraded my web app that utilizes MV6.Lookup and I am now receiving the following error message in my app:

TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ExpressionHelper' from assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
NonFactors.Mvc.Lookup.LookupExtensions.AutoCompleteFor<TModel, TProperty>(IHtmlHelper<TModel> html, Expression<Func<TModel, TProperty>> expression, MvcLookup model, object htmlAttributes)

**Comment by Muchiachio** [comment]
Yes. I'm aware. But I can't fix it yet, because of https://github.com/aspnet/AspNetCore/issues/14378.

**Comment by Muchiachio** [comment]
Fixed in `4.1.0`.

**Comment by Shameer-Ali** [comment]
@Muchiachio , I'm facing the same issue and could you please, let me know how to resolve this issue.

Sorry that i don't under stand in which package this issue fixed? (Fixed in 4.1.0), what did you mean here?

**Comment by Muchiachio** [comment]
It's nuget package version.
