### ISSUE TITLE
how to use the same control for multiple searches , i.e. clear previous search result 

### ISSUE THREAD

**Issue by aliramadan8** [NonFactors/MVC6.Lookup#15]
i use the control and it works perfectly , but if i tried to search again ti starts with the previously chosen value ,how to clear the search value between searched , i need to do this manually something like below 

```
 $("#btnAddapPurchInvD").click(function () {
 
           
            var element = document.querySelector('.mvc-lookup-value');
            element.value="";
          
        });
```

**Comment by Muchiachio** [comment]
Which value are you clearing? Lookup selection? Dialog search input?

**Comment by aliramadan8** [comment]
when you choose a value ,then try to search again ,it start searching with the previous value ,so i need a way to clean the content of it ,so the new search start from scratch 
![image](https://user-images.githubusercontent.com/24622815/70214944-0d354a80-1745-11ea-9dfc-7b58f4dc51ab.png)

**Comment by Muchiachio** [comment]
You can clear the id value you used and then call reload on lookup instance.
```JS
$('#MyInputId').val('');
lookup.reload();
```

**Comment by aliramadan8** [comment]
i have tried the below ,with no success 
```
            var element = document.querySelector('.lkpivItemDetails');
            var lookup = new MvcLookup(element);
            lookup.reload();
```

always return error "Cannot read property 'set' of undefined"

**Comment by Muchiachio** [comment]
Did your first initialization use `.lkpivItemDetails` selector?
Doesn't seem that it would match something inside a lookup dom tree.
