### ISSUE TITLE
Source URL for a shared lookup?

### ISSUE THREAD

**Issue by timotahti** [NonFactors/MVC6.Lookup#3]
Hi,

how can I implement a shared lookup component? For example - Customers: I'd like to implement a single CustomerLookup Controller to handle all customer lookups for different underlying entities (for Orders, Messages etc.) ?

The Url logic seems to use /Orders or /Messages as the base URL, is there any way around this?

Regards,
-Timo

**Comment by Muchiachio** [comment]
Just overwrite `Url` in constructor or that didn't work as expected?

**Comment by Muchiachio** [comment]
Did it work?

**Comment by timotahti** [comment]
Sorry, been offline for a couple of days. Will test and let you know by tomorrow at the latest.

-Timo

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Tue, Jul 12, 2016 at 7:55 PM +0300, "Muchiachio" <notifications@github.com<mailto:notifications@github.com>> wrote:


Did it work?

-

**Comment by timotahti** [comment]
Hi, the constructor fix did not quite do the trick (I already had that in place).

So, here's my scenario:

- URL where I want to create a new Order (the Order has a lookup to Customer) http://localhost:7113/Orders/Create

- I'm setting the URL in the CustomerLookup constructor:  Url = "Customers/Default";

- the final lookup URL ends up looking like this - so it still uses the "Orders" root when mapping the URL. Is it possible to prevent that from happening?

http://localhost:7113/Orders/Customers/Default?SearchTerm=undefined&RecordsPerPage=undefined&SortColumn=FullName&SortOrder=Asc&Page=0&_=1468494057456

**Comment by Muchiachio** [comment]
Yes this is how $.ajax url appending works :smile:
Adding a `/` at the beginning should append to the base path.

**Comment by timotahti** [comment]
Can't believe I missed that. ;)  Works now, thanks!
