### ISSUE TITLE
How to inject repository?

### ISSUE THREAD

**Issue by drodic** [NonFactors/MVC6.Lookup#4]
Hello,

First at all your MVC6.Grid is great component, I use it for some time and have great experience.
That's why I decided to use MVC6.Lookup, but I have some problems.
I followed your example where you use: 

```C#
public override IQueryable<PersonModel> GetModels()
{
    return PeopleRepository.GetPeople();
}
```

I dont know how to inject repository in MvcLookup<T> derived class?
I want to inject repository in constructor, is it possible or there is another solution?

**Comment by Muchiachio** [comment]
Yes, you can inject it though a constructor, I usually pass a context to `LookupController` and then pass it to lookup in action. I will update example pages with this.
```C#
public class LookupController : Controller
{
    private DbContext Context { get; }

    public LookupController(DbContext context)
    {
        Context = context;
    }

    [NonAction]
    public virtual JsonResult GetData(MvcLookup lookup, LookupFilter filter)
    {
        lookup.Filter = filter;

        return Json(lookup.GetData());
    }

    [AjaxOnly]
    public JsonResult Role(LookupFilter filter)
    {
        return GetData(new Lookup(context), filter);
    }
}
```

**Comment by drodic** [comment]
Thank you very much. It works like a charm.
