### ISSUE TITLE
AutocompleteFor cannot be found

### ISSUE THREAD

**Issue by GidoSt** [NonFactors/MVC6.Lookup#5]
I've followed the instructions but seem to have forgotten something or have done something wrong. I'm getting everything built nicely, but get this error when I try to include it in my view. Code is: 

                @Html.AutocompleteFor(model => model.OrganisatieID, new OrganisationLookup())

Does not contain a definition for 'AutocompleteFor' and no extension method 'AutocompleteFor' accepting a first argument of type 'HtmlHelper<LidModel>' could be found (are you missing a using directive or an assembly reference?)	1_Views_Lid_CreateAdmin.cshtml

**Comment by Muchiachio** [comment]
Did you include `@using NonFactors.Mvc.Lookup;` to your page or `_ViewImports.cshtml`?

**Comment by GidoSt** [comment]
I did in viewimports, and added it to my view page as well, but unfortunatly I'm getting the same error. I'm using MVC6 and included your components via NuGet.

**Comment by Muchiachio** [comment]
Strange, does it work when used directly? `NonFactors.Mvc.Lookup.LookupExtensions.AutocompleteFor`.
I also see that your html helper is of type `HtmlHelper` and extensions take `IHtmlHelper<TModel>`, maybe this is one of the problems too?

**Comment by GidoSt** [comment]
Okay, it seems to work when I directly reference it in code. But now I get the following error:

There is no argument given that corresponds to the required formal parameter 'model' of 'LookupExtensions.AutoCompleteFor<TModel, TProperty>(IHtmlHelper<TModel>, Expression<Func<TModel, TProperty>>, MvcLookup, object)'

  @NonFactors.Mvc.Lookup.LookupExtensions.AutoCompleteFor(model => model.OrganisatieID, new OrganisationLookup())
             
Any idea where my mistake might be? Thank you so much for replying.

**Comment by Muchiachio** [comment]
Seems like a constructor problem somewhere, did you inherited the lookup class properly?

**Comment by GidoSt** [comment]
Okay, this one is next... 

My view code looks like this: 
`@NonFactors.Mvc.Lookup.LookupExtensions.AutoCompleteFor(Html, model => model.OrganisatieID, new OrganisationLookup())`

And my lookup code: 
```
 public class OrganisationLookup : MvcLookup<OrganisatieModel>
    {
        private DbContext Context { get; }

        public OrganisationLookup(DbContext context)
        {
            Context = context;
        }
        public OrganisationLookup(Boolean multi = false)
        {
            Url = "AllOrganisations";
            Title = "Organisations";

            Multi = multi;
            Filter.Rows = 5;
            Filter.Sort = "Name";
            Filter.Order = LookupSortOrder.Asc;
        }

        public override IQueryable<OrganisatieModel> GetModels()
        {
            return Context.Set<OrganisatieModel>();
        }
    }
```

The type arguments for method 'LookupExtensions.AutoCompleteFor<TModel, TProperty>(IHtmlHelper<TModel>, Expression<Func<TModel, TProperty>>, MvcLookup, object)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

**Comment by Muchiachio** [comment]
Try specifying the types implicitly in `AutocompleteFor` like this `Autocomplete<MyModel, MyPropertyType>`.

**Comment by GidoSt** [comment]
After some fiddling with brackets, I think I've found the core to the entire problem: 

CS1503: Argument 1: cannot convert from 'System.Web.Mvc.HtmlHelper<PlanningsModule.Models.LidModel>' to 'Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<PlanningsModule.Models.LidModel>'

Seems like it is trying to convert between the new MVC html helper and the old System.Web one.

**Comment by Muchiachio** [comment]
If you are using MVC5, you should be using `Datalist` package.

**Comment by GidoSt** [comment]
Thanks! That made it work! Thanks so much! 

Alright, so I have 1 remaining question;
I want to have a autocomplete lookup for the model 'OrganisationModel' on the 'Create' view of another model, named 'LidModel'. 

I now had this: 
@(Datalist.DatalistExtensions.AutoCompleteFor<LidModel, Guid>(Html,model => model.OrganisatieID, new OrganisatieLookup()))

But that doesn't get me any results in my autocomplete, how would it look if I want to achieve this?

**Comment by Muchiachio** [comment]
Did you search for anything that exists, because it only starts querying data on input?
Also did you add at least one `[DatalistColumn]` to the model? You can use `.DatalistFor` to see all the results for now, until you are sure that everything works, this way it will be easier to debug.

**Comment by GidoSt** [comment]
Thanks for your help so far. I've changed the control to DataListFor, and identified the 'Name' field as DatalistColumn in the model. 

For some reason I can't seem to trigger the "AllOrginizations" event in the controller, I don't know what the problem is, and I can't seem to figure out how to debug it. 

Here is my code: 

View:
` @(Datalist.DatalistExtensions.DatalistFor<LidModel, Guid>(Html, model => model.OrganisatieID, new OrganisatieLookup()))`

Then in the controller: 
`[HttpGet]
        public JsonResult AllOrganizations(DatalistFilter filter)
        {
            OrganisatieLookup datalist = new OrganisatieLookup(db);
            datalist.Filter = filter;

            return Json(datalist.GetData());
        }`

The lookup: 
` public class OrganisatieLookup : MvcDatalist<OrganisatieModel>
    {
        private DbContext Context { get; }

        public OrganisatieLookup(DbContext context)
        {
            Context = context;
        }
        public OrganisatieLookup(Boolean multi = false)
        {
            Url = "AllOrganizations";
            Title = "Organizations";

            Multi = multi;
            Filter.Rows = 5;
            Filter.Sort = "Name";
            Filter.Order = DatalistSortOrder.Asc;
        }

        public override IQueryable<OrganisatieModel> GetModels()
        {
            return Context.Set<OrganisatieModel>();
        }
    }`

Model:
` public class OrganisatieModel
    {
        public Guid ID { get; set; }

        [DatalistColumn]
        [Display(Name = "Organization name")]
        public string Name { get; set; }

        [Display(Name = "Current number of members")]
        public int aantalLeden { get; set; }

        [Display(Name = "Maximum amount of members for subscription")]
        public int maximaalLeden { get; set; }
    }`

**Comment by Muchiachio** [comment]
Check the `Network` tab in your browser, if no calls made at all then you are probably missing initialization code `$('.mvc-lookup').mvclookup();`. If it calls something you can check what is wrong with the url, maybe it's resolved relative to the domain and not the current controller.

**Comment by GidoSt** [comment]
Alright, the browser debugger showed me a bit more, I'm getting the following error in the console: 
SCRIPT438: Object doesn't support property or method 'autocomplete'

**Comment by Muchiachio** [comment]
Do you have a version of `jquery-ui.js` with autocomplete plugin included in your page?
And did you follow installation instructions [here](http://mvc-lookup.azurewebsites.net/Home/Installation)?

**Comment by GidoSt** [comment]
Thanks a lot, apparantly I've removed jquery UI when reinstalling the proper version, now, the control works for selecting, however when I've selected a value and try to save, it gives me a validation message the field is required, and will not save. 

Any ideas?

**Comment by Muchiachio** [comment]
I'm not sure, could you create a small repro?

**Comment by Muchiachio** [comment]
Did you managed to resolve your issues?
