### ISSUE TITLE
Control shows lookup key after selecting

### ISSUE THREAD

**Issue by MohdRash** [NonFactors/MVC6.Lookup#6]
Hi,

Thank alot for the amazing control. However, I am facing an issue which is that the lookup control is showing the lookup key rather than the lookup value after selecting the elements.

**Comment by Muchiachio** [comment]
You mean it shows lookup id? By default it shows first lookup column as selected value, also it's not necessary to include lookup key (id) as a column, if you don't show it as a value.

**Comment by MohdRash** [comment]
Hi,

Great. It was fixed! Just changed the sequence of properties.
I am just curious if there is a way to change this default behavior or is possible to explicitly choose a property as a display value when selected rather than requiring the very first lookup column property.

**Comment by Muchiachio** [comment]
Yes, you can. [Here's](http://mvc-lookup.azurewebsites.net/Lookup/Autocomplete) an example on how to do that.
You can also set lookup's `Autocomplete` function property in your controller.

**Comment by MohdRash** [comment]
Great. Works perfectly.
One final question is regarding bootstrap. It seems the control is not bootstrap friendly as I am facing problems on aligning.

**Comment by Muchiachio** [comment]
It should work fine with bootstrap v3, didn't test with v4.

**Comment by MohdRash** [comment]
Great. Thanks alot.
