### ISSUE TITLE
How to reload for multiple selection?

### ISSUE THREAD

**Issue by aungnemyo** [NonFactors/MVC6.Lookup#8]
I would like to reload for multiple selection in editing form.
By the way, this lookup is very useful.

**Comment by Muchiachio** [comment]
Supported way is initialization `@Html.Lookup("Id", new PeopleLookup { Multi = true }, new[] { 1, 3 })`.
Doing it on javascript is only possible only through hacks.

**Comment by aungnemyo** [comment]
I need to reload for multi selection lookup on javascript only, how can i try to do this?

**Comment by Muchiachio** [comment]
I guess this would be the simplest hack:
```JS
$('.mvc-lookup').mvclookup('instance').select([{ LookupIdKey: 1 }, { LookupIdKey: 2 }], true);
$('.mvc-lookup').mvclookup('reload');
```

**Comment by aungnemyo** [comment]
This work for me.
Thanks a lot.
